project:
  type: website

execute:
  freeze: auto

website:
  title: "Rachel's Blog"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data-science-final-project/index.qmd
       
  sidebar:
    - id: data-science-final-project
      title: "Final Project"
      style: "docked"
      background: "#ffffff"
      collapse-level: 5
      contents: 
        - data-science-final-project/index.qmd
        - data-science-final-project/sources.qmd
        - data-science-final-project/graphs_1.qmd
    
    - title: "Hello"
      


format:
  html:
    theme: flatly
    css: styles.css
    toc: true



