---
title: "Final project"
---

bloooop

```{r,echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(MetBrewer)

broadway <- read_rds("clean_data.rds")

```

## thing

```{r, Ticket Price Graph, echo = FALSE, warning = FALSE, message = FALSE}
plot_ticket_price_graph <- read_rds("plot_average_ticket_price.rds")
plot_ticket_price_graph
```

```{r, avg capacity graph, echo = FALSE, warning = FALSE, message = FALSE}
plot_avg_pct_cap_graph <- read_rds("plot_pct_cap.rds")
plot_avg_pct_cap_graph 
```

## thing2

here's a paragraph avlkasdflkj o;qwe aslkdjf;lk aoier l;askdfj 

```{r, top shows graph, echo = FALSE, warning = FALSE, message = FALSE}
plot_top_shows_graph <- read_rds("plot_top_shows.rds")
plot_top_shows_graph
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
plot_pct_vs_cap_graph <- read_rds("plot_interactive_pct_vs_cap.rds")
plot_pct_vs_cap_graph
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
plot_avg_top_shows_tickets_graph <- read_rds("plot_avg_top_shows_tickets_graph.rds")
plot_avg_top_shows_tickets_graph
```

